---
- 
- name: Install a gnupg package.
  apt:
    name: gnupg
    state: present

- name: Import an apt key.
  apt_key:
    url: '{{ mariadb_apt_key }}'
    state: present
  when:
    - mariadb_debian_repo | length > 0
    - mariadb_apt_key | length > 0

- name: Configure apt repository.
  apt_repository:
    repo: 'deb {{ mariadb_debian_repo }} {{ ansible_distribution_release }} main'
    state: present
    filename: mariadb
  when:
    - mariadb_debian_repo | length > 0